import React from 'react';
import { clsx } from 'clsx';
import { SparklesIcon, ArrowDownIcon, ArrowUpIcon } from '@heroicons/react/24/outline';

/**
 * WhatIfOptimizer — Mode C. Shows the original toxic molecule and ranked
 * structural modifications (counterfactuals) with predicted toxicity change.
 */
const WhatIfOptimizer = ({ whatif }) => {
  if (!whatif || whatif.candidates?.length === 0) {
    return (
      <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-400">
        Enter a molecule in <b>Mode C</b> to generate toxicity-lowering modifications.
      </div>
    );
  }

  const originalSmiles = whatif.original_smiles;
  const candidates = whatif.candidates || [];

  const originalTox = candidates.length
    ? (whatif.baseline_toxicity ?? Math.max(...candidates.map((c) => c.toxicity_probability + 0.0001)))
    : 0;

  return (
    <div className="space-y-5">
      <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
        <p className="text-xs font-semibold uppercase text-slate-400">Original Molecule</p>
        <p className="mt-1 break-all font-mono text-sm text-slate-700">{originalSmiles}</p>
      </div>

      <h3 className="text-sm font-bold uppercase tracking-wide text-slate-500">
        Suggested Modifications ({candidates.length})
      </h3>

      <div className="space-y-3">
        {candidates.map((c, i) => {
          const delta = (c.toxicity_probability ?? 0) - originalTox;
          const lowered = delta < 0;
          return (
            <div key={i} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                  <p className="text-sm font-bold text-slate-700">{c.modification_description}</p>
                  <p className="mt-1 break-all font-mono text-xs text-slate-500">{c.modified_smiles}</p>
                </div>
                <div className="flex items-center gap-4">
                  <div className="text-right">
                    <p className="text-xs text-slate-400">Toxicity</p>
                    <p className="text-lg font-black text-slate-700">
                      {((c.toxicity_probability ?? 0) * 100).toFixed(0)}%
                    </p>
                  </div>
                  <div
                    className={clsx(
                      'flex items-center gap-1 rounded-full px-3 py-1 text-sm font-bold',
                      lowered ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'
                    )}
                  >
                    {lowered ? <ArrowDownIcon className="h-4 w-4" /> : <ArrowUpIcon className="h-4 w-4" />}
                    {delta >= 0 ? '+' : ''}
                    {(delta * 100).toFixed(0)}%
                  </div>
                </div>
              </div>
              <p className="mt-2 flex flex-wrap items-center gap-2 text-xs text-slate-400">
                <span>Expected effect: {c.expected_toxicity_change}</span>
                <span>· confidence {(c.confidence * 100).toFixed(0)}%</span>
                {c.qed != null && (
                  <span
                    className={clsx(
                      'rounded-full px-2 py-0.5 font-semibold',
                      c.qed >= 0.4 ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'
                    )}
                    title="Quantitative Estimate of Drug-likeness (RDKit QED)"
                  >
                    QED {c.qed.toFixed(2)}{c.qed >= 0.4 ? ' · drug-like' : ''}
                  </span>
                )}
              </p>
            </div>
          );
        })}
      </div>

      <p className="flex items-center gap-2 text-xs italic text-slate-400">
        <SparklesIcon className="h-4 w-4" />
        Candidates are generated by chemically valid perturbations and re-scored through the multi-task GNN.
        Reduced-toxicity modifications are prioritized while ADMET properties are preserved where possible.
      </p>
    </div>
  );
};

export default WhatIfOptimizer;
